# Generated by Django 4.1 on 2023-09-08 12:40

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boxes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered', models.BooleanField(default=False, null=True)),
                ('topic', models.TextField(default='family', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(default='user', max_length=50, null=True)),
                ('topic', models.TextField(default=None, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(default=None, null=True)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('public', models.BooleanField(default=True, null=True)),
                ('anonymous', models.BooleanField(default=False, null=True)),
                ('post', models.BooleanField(default=False, null=True)),
                ('edited', models.BooleanField(default=False, null=True)),
                ('box', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_box.boxes')),
            ],
        ),
        migrations.AddField(
            model_name='boxes',
            name='answered_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers_user', to='question_box.newuser'),
        ),
        migrations.AddField(
            model_name='boxes',
            name='asked_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asks_user', to='question_box.newuser'),
        ),
        migrations.AddField(
            model_name='boxes',
            name='confirmed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comfirms_user', to='question_box.newuser'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None, null=True)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('confirmed', models.BooleanField(default=False, null=True)),
                ('edited', models.BooleanField(default=False, null=True)),
                ('post', models.BooleanField(default=False, null=True)),
                ('box', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='question_box.boxes')),
            ],
        ),
    ]
