# Generated by Django 4.1 on 2023-09-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0001_initial'),
    ]

    operations = [
    ]
