# Generated by Django 4.1 on 2023-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0002_auto_20230908_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='hi',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
