# Generated by Django 4.1 on 2023-09-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_box', '0003_newuser_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='hi',
        ),
    ]
